php-fpm:
  image: openbridge/php-fpm
  volumes:
    - /ebs:/ebs
  environment:
    - ob_mode=aws
    - ob_tag=php-fpm
  ports:
    - "9000:9000"
  expose:
    - 9000
  restart: always
  tty: true
  container_name: php-fpm
  ulimits:
    nproc: 65535
    nofile:
        soft: 49999
        hard: 99999
