hhvm:
  image: openbridge/hhvm
  volumes:
    - /ebs:/ebs
  environment:
    - ob_mode=aws
    - ob_tag=hhvm
  ports:
    - "8000:8000"
  expose:
    - 8000
  restart: always
  tty: true
  container_name: hhvm
  ulimits:
    nproc: 65535
    nofile:
        soft: 49999
        hard: 99999
